name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependency
        run: yarn install
      - name: Lint
        run: yarn lint
