name: Server

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependency
        run: yarn install
      - name: Build types and lib
        run: |
          yarn build:lib
          yarn build:types
      - name: Build UI
        run: yarn build:ui
      - name: Test
        run: yarn test